version: "3.8"
services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    hostname: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
    volumes:
      - ./database/data:/data/db
    ports:
      - 27017:27017
    networks:
      - backend

  mongo-express:
    image: mongo-express
    container_name: mongo-ui
    restart: unless-stopped
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=
      - ME_CONFIG_MONGODB_ADMINPASSWORD=
      - ME_CONFIG_MONGODB_URL=
      - ME_CONFIG_BASICAUTH_USERNAME=
      - ME_CONFIG_BASICAUTH_PASSWORD=
    ports:
      - 8081:8081
    networks:
      - backend
    links:
      - mongo:mongo
    depends_on:
      - mongo

  admin:
    build:
      target: production
      dockerfile: ./docker/Dockerfile.admin
    container_name: admin
    restart: unless-stopped
    env_file: ./admin/.env
    environment:
      - NODE_ENV=production
    ports:
      - "30002:3002"
    networks:
      - client

  client:
    build:
      target: production
      dockerfile: ./docker/Dockerfile.client
    container_name: client
    restart: unless-stopped
    env_file: ./client/.env
    environment:
      - NODE_ENV=production
    ports:
      - "30001:3001"
    networks:
      - client

  server:
    build:
      target: production
      dockerfile: ./docker/Dockerfile.server
    container_name: server
    restart: unless-stopped
    env_file: ./server/.env
    environment:
      - NODE_ENV=production
      - MONGO_DB_LINK=mongodb://mongo:27017
      - MONGO_DB_AUTH_USERNAME=
      - MONGO_DB_AUTH_PASSWORD=
      - MONGO_DB_NAME=
      - SECRET=
      - D_ADMIN_KEY=
    volumes:
      - ./server/public/:/app/server/public
    ports:
      - 30000:3000
    networks:
      - client
      - backend
    depends_on:
      - mongo
    links:
      - mongo

networks:
  client:
    driver: bridge
  backend:
    driver: bridge

volumes:
  database:
    driver: local
