version: '3.8'
services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    hostname: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=admin123
    volumes:
      - ./database/data:/data/db
    ports:
      - 30004:27017
    networks:
      - backend

  mongo-express:
    image: mongo-express
    container_name: mongo-ui
    restart: unless-stopped
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin123
      - ME_CONFIG_MONGODB_URL=mongodb://root:admin123@mongo:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=mexpress
      - ME_CONFIG_BASICAUTH_PASSWORD=mexpress
    ports:
      - 8081:8081
    networks:
      - backend
    links:
      - mongo:mongo
    depends_on:
      - mongo

  admin:
    build:
      context: ./admin
      target: production
      dockerfile: Dockerfile
    container_name: admin
    restart: unless-stopped
    env_file: ./admin/.env.example
    environment:
      - NODE_ENV=production
    ports:
      - '30002:3002'
    networks:
      - frontend
    
  client:
    build:
      context: ./client
      target: production
      dockerfile: Dockerfile
    container_name: client
    restart: unless-stopped
    env_file: ./client/.env.example
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SERVER_API_KEY=47174ee70e4e144d3de4212f9ce09a004315772bae5b648c067bbcd0c54ca5a6848ed744867cfddcce63ec11f02e433908ae85463a3c8f16cf03ace88ae60434e7f7bf5ff15e3aece0ec1ddda294504033c12d38176ad5fbb86655ff8e8b6f544ee05f54c93435dfdd264223d5c0733e4816bbeffca7d27d34e71f83fbf84848
    ports:
      - '30001:3001'
    networks:
      - frontend
  
  server:
    build:
      context: ./server
      target: production
      dockerfile: Dockerfile
    container_name: server
    restart: unless-stopped
    env_file: ./server/.env.example
    environment:
      - NODE_ENV=production
      - MONGO_DB_LINK=mongodb://mongo:27017
      - MONGO_DB_NAME=fixlab-db
      - MONGO_DB_AUTH_USERNAME=root
      - MONGO_DB_AUTH_PASSWORD=admin123
      - SECRET=4u5I577c6zTbw7za
    ports:
      - 30000:3000
    networks:
      - frontend
      - backend
    depends_on:
      - mongo
    links:
      - mongo

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  database:
    driver: local