name: CI/CD Build Pipeline # The name of the workflow

on:
  pull_request:
    branches:
      - "*"
    types: [labeled]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build:
    name: "Build Application"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v3

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v3

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: "Build Server"
        if: ${{ github.event.label.name == 'backend' }}
        uses: docker/build-push-action@v4
        with:
          context: ./server
          target: production
          secrets: |
            MONGO_DB_AUTH_USERNAME=${{ secrets.MONGO_INITDB_ROOT_USERNAME }}
            MONGO_DB_AUTH_PASSWORD=${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}
            SECRET=${{ secrets.SECRET }}
            D_ADMIN_KEY=${{ secrets.D_ADMIN_KEY }}
          push: true
          tags: |
            ghcr.io/iryna-gry/prod-fixlab-server:latest

      - name: "Build Client"
        if: ${{ github.event.label.name == 'frontend-client' }}
        uses: docker/build-push-action@v4
        with:
          context: ./client
          target: production
          push: true
          tags: |
            ghcr.io/iryna-gry/prod-fixlab-client:latest

      - name: "Build Admin"
        if: ${{ github.event.label.name == 'frontend-admin' }}
        uses: docker/build-push-action@v4
        with:
          context: ./admin
          target: production
          push: true
          tags: |
            ghcr.io/iryna-gry/prod-fixlab-admin:latest
